name: dbt CI Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - ci

permissions:
  contents: write
  pull-requests: write

jobs:
  ci_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install dbt-snowflake

      - name: Set up dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_CREDENTIALS }}" > ~/.dbt/profiles.yml

      - name: Clone CI database
        if: (github.ref == 'refs/heads/ci') || (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'ci')
        run: |
          source venv/bin/activate
          dbt run-operation ci_clone_db

      - name: Run dbt Commands
        if: (github.ref == 'refs/heads/ci') || (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'ci')
        run: |
          source venv/bin/activate
          dbt deps
          dbt seed
          dbt run
          dbt test

      - name: Grant CI database access
        if: (github.ref == 'refs/heads/ci') || (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'ci')
        run: |
          source venv/bin/activate
          dbt run-operation grant_view_access

      - name: Drop CI databases
        if: (github.ref == 'refs/heads/main') || (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main')
        run: |
          source venv/bin/activate
          dbt run-operation ci_drop_db
  pr_main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/ci'  # Runs only when changes are pushed to 'ci' branch
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Create PR from CI to Main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git checkout ci
          git pull origin ci
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/pulls \
               -d '{"title":"Automated PR: Merge CI changes to main","head":"ci","base":"main","body":"This is an automated PR to merge changes from ci to main after merging dev to ci."}'
  pre_commit_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pre-commit dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install pre-commit
          pre-commit install
          pip install dbt-snowflake

      - name: Set up dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_CREDENTIALS }}" > ~/.dbt/profiles.yml

      - name: Run pre-commit hooks
        run: |
          source venv/bin/activate
          pre-commit run --all-files
