version: 2

sources:
  - name: hubspot
    description: Hubspot data
    database: RAW
    schema: HUBSPOT
    loader: seed_table                                  # WHo loaded this source? eg: Fivetran, Stitch, snowpipe, and etc...,
    # loaded_at_field: <column_name>
    meta:
        data_provider: hubspot                          # Enter the data provider name
        environment: Test_data                          # mention the type of data, whether its UAT/ live data's
    tags: ['external', 'hubspot']

    tables:
      - name: customer                                   # referred names in dbt model
        identifier: CUSTOMERS                            # actual table name in Snowflake, by using this variable we can avoid to update the table name in multiple models
        freshness:
          warn_after: {count: 6, period: hour}
          error_after: {count: 12, period: hour}
        loaded_at_field: created_at
      - name: project  
        identifier: PROJECTS 
  
  - name: jin
    description: Jin data
    database: RAW
    schema: JIN
    loader: Seed_table
    # loaded_at_field: <column_name>
    meta:
        data_provider: jin
    tags: ['internal', 'jin']

    tables:
      - name: contact
        identifier: CONTACTS
      - name: employee
        identifier: EMPLOYEES

        
